name: kongke-cd

on:
  push:
    branches:
      - main

jobs:
  build-push-docker:
    name: build-push-docker
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: create .env file
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          touch .env
          echo "ENV=${{ secrets.ENV }}" > .env
          cat .env
          chmod 777 .env
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t sultanfariz/kongke:1.0.0 .
      - name: connect registry docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker
        run: docker push sultanfariz/kongke:1.0.0

  deployment-ec2:
    name: deployment-ec2
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: ssh config
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/pinjem.pem
          chmod 400 ~/.ssh/kongke.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/kongke.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) && docker pull sultanfariz/kongke:1.0.0 && docker run -d -p 8080:8080 --name kongke sultanfariz/kongke:1.0.0'
